# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#2d3748"
background = "#f7fafc"
dim_foreground = "#718096"
bright_foreground = "#1a202c"

[colors.cursor]
text = "#2d3748"
cursor = "#3182ce"

[colors.vi_mode_cursor]
text = "#2d3748"
cursor = "#3182ce"

[colors.search.matches]
foreground = "#718096"
background = "#e2e8f0"

[colors.search.focused_match]
foreground = "#f7fafc"
background = "#3182ce"

[colors.hints.start]
foreground = "#718096"
background = "#edf2f7"

[colors.hints.end]
foreground = "#3182ce"
background = "#edf2f7"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#2d3748"
background = "#edf2f7"

[colors.selection]
text = "#2d3748"
background = "#cbd5e0"

[colors.normal]
black = "#e2e8f0"
red = "#e53e3e"
green = "#38a169"
yellow = "#d69e2e"
blue = "#3182ce"
magenta = "#805ad5"
cyan = "#319795"
white = "#4a5568"

[colors.bright]
black = "#cbd5e0"
red = "#f56565"
green = "#48bb78"
yellow = "#ecc94b"
blue = "#4299e1"
magenta = "#9f7aea"
cyan = "#38b2ac"
white = "#2d3748"

[colors.dim]
black = "#cbd5e0"
red = "#c53030"
green = "#2f855a"
yellow = "#b7791f"
blue = "#2b6cb0"
magenta = "#553c9a"
cyan = "#2c7a7b"
white = "#4a5568" 