# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#C1C497"
background = "#111c18"
dim_foreground = "#9eebb3"
bright_foreground = "#F6F5DD"

[colors.cursor]
text = "#000000"
cursor = "#D7C995"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#D7C995"

[colors.search.matches]
foreground = "#C1C497"
background = "#23372B"

[colors.search.focused_match]
foreground = "#111c18"
background = "#2DD5B7"

[colors.hints.start]
foreground = "#C1C497"
background = "#23372B"

[colors.hints.end]
foreground = "#9eebb3"
background = "#23372B"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#C1C497"
background = "#23372B"

[colors.selection]
text = "#C1C497"
background = "#53685B"

[colors.normal]
black = "#23372B"
red = "#FF5345"
green = "#549e6a"
yellow = "#459451"
blue = "#509475"
magenta = "#D2689C"
cyan = "#2DD5B7"
white = "#F6F5DD"

[colors.bright]
black = "#53685B"
red = "#db9f9c"
green = "#143614"
yellow = "#E5C736"
blue = "#ACD4CF"
magenta = "#75bbb3"
cyan = "#8CD3CB"
white = "#9eebb3"

[colors.dim]
black = "#53685B"
red = "#db9f9c"
green = "#143614"
yellow = "#E5C736"
blue = "#ACD4CF"
magenta = "#75bbb3"
cyan = "#8CD3CB"
white = "#9eebb3"