[colors.primary]
foreground = "#bebebe"
background = "#121212"
dim_foreground = "#8a8a8d"
bright_foreground = "#eaeaea"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.search.matches]
foreground = "#bebebe"
background = "#333333"

[colors.search.focused_match]
foreground = "#121212"
background = "#f59e0b"

[colors.hints.start]
foreground = "#bebebe"
background = "#333333"

[colors.hints.end]
foreground = "#8a8a8d"
background = "#333333"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#bebebe"
background = "#333333"

[colors.selection]
text = "#bebebe"
background = "#333333"

[colors.normal]
black = "#333333"
red = "#D35F5F"
green = "#FFC107"
yellow = "#b91c1c"
blue = "#e68e0d"
magenta = "#D35F5F"
cyan = "#bebebe"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#B91C1C"
green = "#FFC107"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#B91C1C"
cyan = "#eaeaea"
white = "#ffffff"

[colors.dim]
black = "#8a8a8d"
red = "#B91C1C"
green = "#FFC107"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#B91C1C"
cyan = "#eaeaea"
white = "#ffffff"