#!/usr/bin/env bash

# Color functions
color_reset="\033[0m"
color_info="\033[1;34m"    # Bold Blue
color_success="\033[1;32m" # Bold Green
color_warn="\033[1;33m"    # Bold Yellow
color_error="\033[1;31m"   # Bold Red

log_info() { echo -e "${color_info}info: ${color_reset} $*"; }
log_warn() { echo -e "${color_warn}warning: ${color_reset} $*"; }
log_error() { echo -e "${color_error}error: ${color_reset} $*"; }
log_success() { echo -e "${color_success}success: ${color_reset} $*"; }

section() {
	echo -e "\n${color_info}===== [ $* ] =====${color_reset}\n"
}

USE_SUDO=false

run_with_sudo() {
	if [ "$USE_SUDO" = true ]; then
		sudo "$@"
	else
		"$@"
	fi
}

with_sudo() {
	USE_SUDO=true
	"$@"
	USE_SUDO=false
}

create_backup_and_delete() {
	local file="$1"

	if run_with_sudo test -L "$file"; then
		# log_warn "file $file is a symlink, no backup created."
		run_with_sudo rm -f "$file" && log_info "removed symlink: $file"
		return 0
	fi

	if ! run_with_sudo test -e "$file"; then
		# log_warn "file $file does not exist, no backup created."
		return 0
	fi

	run_with_sudo cp -rf "$file" "${file}.bak" && log_info "backup created: ${file}.bak" && run_with_sudo rm -rf "$file" && log_info "removed file: $file"
}

create_backup() {
	local file="$1"

	if run_with_sudo test -L "$file"; then
		# log_warn "file $file is a symlink, no backup created."
		return 0
	fi

	if ! run_with_sudo test -e "$file"; then
		# log_warn "file $file does not exist, no backup created."
		return 0
	fi

	run_with_sudo cp -rf "$file" "${file}.bak" && log_info "backup created: ${file}.bak"
}

create_symlink() {
	local target="$1"
	local link_name="$2"

	if ! run_with_sudo test -e "$target" && run_with_sudo -e "$link_name"; then
		log_warn "target $target does not exist, but existing $link_name will be copied instead."
		run_with_sudo cp -rf "$link_name" "$target" && log_info "copied $link_name to $target"
	fi

	create_backup_and_delete "$link_name" && run_with_sudo mkdir -p "$(dirname "$link_name")" && run_with_sudo ln -sT "$target" "$link_name" && log_info "created symlink: $link_name -> $target"
}

create_dotfiles_symlink() {
	create_symlink "$DOTFILES_DIR/config/$1" "$2"
}

create_copy() {
	local source="$1"
	local destination="$2"

	create_backup_and_delete "$destination" && run_with_sudo mkdir -p "$(dirname "$destination")" && run_with_sudo cp "$source" "$destination" && log_info "copied $source to $destination"
}

create_recursive_copy() {
	local source="$1"
	local destination="$2"

	create_backup_and_delete "$destination" && run_with_sudo mkdir -p "$(dirname "$destination")" && run_with_sudo cp -r "$source" "$destination" && log_info "recursively copied $source to $destination"
}

create_dotfiles_copy() {
	create_copy "$DOTFILES_DIR/config/$1" "$2"
}

create_dotfiles_recursive_copy() {
	create_recursive_copy "$DOTFILES_DIR/config/$1" "$2"
}

# FIXME: does not seem to work multiple times when the marker is first line
insert_content_with_marker() {
	local file="$1" marker="$2" content="$3" comment_char_opening="${4:-#}" comment_char_closing="${5:-#}"
	local start="$comment_char_opening AUTOGENERATED START $marker $comment_char_closing"
	local end="$comment_char_opening AUTOGENERATED END $marker $comment_char_closing"

	# Create temp file to preserve original location
	local temp_file=$(mktemp)

	if run_with_sudo grep -Fq "$start" "$file" 2>/dev/null; then
		# Replace content between markers
		local start_line=$(run_with_sudo grep -Fn "$start" "$file" | cut -d: -f1)
		local end_line=$(run_with_sudo grep -Fn "$end" "$file" | cut -d: -f1)

		# Copy before, insert new content, copy after
		{
			run_with_sudo head -n $((start_line - 1)) "$file" 2>/dev/null || true
			printf '%s\n%s\n%s\n' "$start" "$content" "$end"
			run_with_sudo tail -n +$((end_line + 1)) "$file" 2>/dev/null || true
		} >"$temp_file"
		run_with_sudo cp "$temp_file" "$file"
	else
		# Append new content if markers don't exist
		run_with_sudo cp "$file" "$temp_file"
		printf '%s\n%s\n%s\n' "$start" "$content" "$end" >>"$temp_file"
		run_with_sudo cp "$temp_file" "$file"
	fi

	rm -f "$temp_file"
	log_info "inserted content with marker $marker in $file"
}

install_packages() {
	local packages=("$@")

	if [ ${#packages[@]} -eq 0 ]; then
		log_warn "no packages specified for installation."
		return 1
	fi

	log_info "installing packages: ${packages[*]}"
	sudo pacman -S --noconfirm --needed "${packages[@]}"
}

uninstall_packages() {
	local packages=("$@")

	if [ ${#packages[@]} -eq 0 ]; then
		log_warn "no packages specified for uninstallation."
		return 1
	fi

	log_info "uninstalling packages: ${packages[*]}"
	sudo pacman -R --noconfirm "${packages[@]}"
}

install_yay_packages() {
	local packages=("$@")

	if [ ${#packages[@]} -eq 0 ]; then
		log_warn "no yay packages specified for installation."
		return 1
	fi

	log_info "installing yay packages: ${packages[*]}"
	yay -S --needed "${packages[@]}"
}
