#!/usr/bin/env bash

# Function to create a symbolic link but ask for backup if it already exists
create_symlink() {
	local target="$1"
	local link_name="$2"

	if [ -e "$link_name" ]; then
		echo "File $link_name already exists. Backup will be created."
		mv --interactive "$link_name" "${link_name}.bak"
		echo "Backup created: ${link_name}.bak"
	fi

	ln -sT "$target" "$link_name"
	echo "Created symlink: $link_name -> $target"
}

# Snapshot tool setup
read -p "Do you want to setup snapshot tool (Timeshift) ? (y/n)" setup_snapshot_tool
if [[ $setup_snapshot_tool == "y" ]]; then
	# WARNING: The boot on snapshot part (managed by grub-btrfs) will only work with EndeavourOS because it uses dracut.
	# For raw Arch Linux system, see grub-btrfs docs for more information and the alternative way to boot on snapshot.
	sudo pacman -S snapper snap-pac inotify-tools grub-btrfs
	sudo snapper -c root create-config /

	sudo cp --interactive /etc/snapper/configs/root /etc/snapper/configs/root.bak
	sudo snapper -c root set-config ALLOW_USERS="$USER"
	sudo snapper -c root set-config TIMELINE_LIMIT_HOURLY="10"
	sudo snapper -c root set-config TIMELINE_LIMIT_DAILY="5"
	sudo snapper -c root set-config TIMELINE_LIMIT_WEEKLY="3"
	sudo snapper -c root set-config TIMELINE_LIMIT_MONTHLY="0"
	sudo snapper -c root set-config TIMELINE_LIMIT_YEARLY="0"

	sudo systemctl enable --now snapper-timeline.timer snapper-cleanup.timer

	# WARNING: only work on EndeavourOS because it uses dracut
	sudo cp --interactive /etc/default/grub-btrfs/config /etc/default/grub-btrfs/config.bak
	if ! grep -q "GRUB_BTRFS_SNAPSHOT_KERNEL_PARAMETERS=\"rd.live.overlay.overlayfs=1\"" /etc/default/grub-btrfs/config; then
		sudo echo "# AUTOGENERATED GRUB_BTRFS_SNAPSHOT_KERNEL_PARAMETERS"
		sudo echo "GRUB_BTRFS_SNAPSHOT_KERNEL_PARAMETERS=\"rd.live.overlay.overlayfs=1\"" | sudo tee -a /etc/default/grub-btrfs/config
	fi
	sudo systemctl enable --now grub-btrfsd

	sudo snapper -c root create --description "Initial snapshot after first boot and installation of necessary packages"
fi

# System
sudo cp --interactive ~/dotfiles/system/sudoers/florian /etc/sudoers.d/florian
create_symlink ~/dotfiles/system/user-dirs.dirs ~/.config/user-dirs.dirs

# Audio
sudo pacman -S sof-firmware pipewire wireplumber pipewire-audio pipewire-pulse pipewire-jack

# Bashrc and Profile
create_symlink ~/dotfiles/shell/.bashrc ~/.bashrc-default
if ! grep -q "AUTOGENERATED Default bashrc for user" ~/.bashrc; then
	echo "# AUTOGENERATED Default bashrc for user" >>~/.bashrc
	echo "source ~/.bashrc-default" >>~/.bashrc
fi
create_symlink ~/dotfiles/shell/.profile ~/.profile-default
if ! grep -q "AUTOGENERATED Default profile for user" ~/.bash_profile; then
	echo "# AUTOGENERATED Default profile for user" >>~/.bash_profile
	echo "source ~/.profile-default" >>~/.bash_profile
fi

# Bat
sudo pacman -S bat
mkdir -p "$(bat --config-dir)"
create_symlink ~/dotfiles/bat "$(bat --config-dir)"
bat cache --build

sudo pacman -S fd

sudo pacman -S zoxide

sudo pacman -S man-pages

# Hyprland
sudo pacman -S hyprland hyprpaper hyprcursor hyprlock hypridle hyprland-qtutils hyprland-qt-support hyprpolkitagent
sudo pacman -S xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
sudo pacman -S qt6-wayland qt5-wayland

read -p "Do you want to install the Hyprland plugins? (y/n): " install_plugins
if [[ $install_plugins == "y" ]]; then
	# TODO: Check why hyprpm ask the sudo password
	sudo pacman -S cmake meson cpio git gcc
	read -p "Enter the version of hyprland-plugins (e.g. v0.48.0): " plugins_version
	hyprpm add https://github.com/hyprwm/hyprland-plugins $plugins_version
	hyprpm enable hyprexpo
fi
touch ~/.config/hypr/hyprland/custom.conf
create_symlink ~/dotfiles/hypr ~/.config/hypr

# Hyprland uwsm
sudo pacman -S uwsm libnewt

# System controls
sudo pacman -S brightnessctl playerctl
sudo pacman -S power-profiles-daemon
yay -S bluetuith

# Waybar
sudo pacman -S waybar
sudo pacman -S upower
create_symlink ~/dotfiles/waybar ~/.config/waybar

# Thunar
sudo pacman -S thunar

# Kvantum
sudo pacman -S kvantum kvantum-qt5
create_symlink ~/dotfiles/kvantum ~/.config/Kvantum

# Gtk look
sudo pacman -S nwg-look

# Swaync
sudo pacman -S swaync
create_symlink ~/dotfiles/swaync ~/.config/swaync

# Wofi
sudo pacman -S wofi
create_symlink ~/dotfiles/wofi ~/.config/wofi

# Alacritty
sudo pacman -S alacritty
create_symlink ~/dotfiles/alacritty ~/.config/alacritty

# Starship
sudo pacman -S starship
create_symlink ~/dotfiles/starship/starship.toml ~/.config/starship.toml

# Icons
create_symlink ~/dotfiles/icons ~/.local/share/icons

# NodeJS
sudo pacman -S nvm
source ~/.bashrc
nvm install --lts

# TLDR
sudo pacman -S tldr

# Fonts
sudo pacman -S ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols

# Neovim
sudo pacman -S neovim
sudo pacman -S wl-clipboard
create_symlink ~/dotfiles/nvim ~/.config/nvim

# Ripgrep
sudo pacman -S ripgrep

# Fzf
sudo pacman -S fzf
mkdir -p ~/.local/bin/fzf
create_symlink ~/dotfiles/fzf/rose-pine.sh ~/.local/bin/fzf/rose-pine.sh

# Btop
sudo pacman -S btop
mkdir -p ~/.config/btop
create_symlink ~/dotfiles/btop/btop.conf ~/.config/btop/btop.conf
create_symlink ~/dotfiles/btop/themes ~/.config/btop/themes

# Fastfetch
sudo pacman -S fastfetch

# Git
create_symlink ~/dotfiles/gitconfig/linux/.gitconfig ~/.gitconfig-default
if ! grep -q "~/.gitconfig-default" ~/.gitconfig; then
	echo "[include]" >>~/.gitconfig
	echo "	path = ~/.gitconfig-default" >>~/.gitconfig
fi
sudo pacman -S git-filter-repo

# Hyprland autostart
read -p "Do you want to set Hyprland as default? (y/n): " set_hyprland
if [[ $set_hyprland == "y" ]]; then
	if ! grep -q "# AUTOGENERATED Hyprland autostart" ~/.bash_profile; then
		echo "# AUTOGENERATED Hyprland autostart" >>~/.bash_profile
		echo "if uwsm check may-start; then" >>~/.bash_profile
		echo "	exec uwsm start hyprland.desktop" >>~/.bash_profile
		echo "fi" >>~/.bash_profile
	fi
fi

read -p "Do you want to create a snapshot after installation of all packages and configuration files? (y/n): " create_snapshot
if [[ $create_snapshot == "y" ]]; then
	sudo snapper -c root create --description "After installation of all packages and configuration files"
fi
