[package]
name = "appimage"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
askama = "0.14.0"
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
dirs = "6.0.0"
regex = "1.11.1"
rust-ini = "0.21.2"
tempfile = "3.20.0"
thiserror = "2.0.12"

[build-dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
