#!/usr/bin/env bash

create_backup_and_delete() {
	local file="$1"

	if sudo test -L "$file"; then
		echo "File $file is a symlink, no backup created."
		sudo rm -f "$file" && echo "Removed symlink: $file"
		return 0
	fi

	if ! sudo test -e "$file"; then
		echo "File $file does not exist, no backup created."
		return 0
	fi

	sudo cp -rf "$file" "${file}.bak" && echo "Backup created: ${file}.bak" && sudo rm -rf "$file" && echo "Removed file: $file"
}

create_backup() {
	local file="$1"

	if sudo test -L "$file"; then
		echo "File $file is a symlink, no backup created."
		return 0
	fi

	if ! sudo test -e "$file"; then
		echo "File $file does not exist, no backup created."
		return 0
	fi

	sudo cp -rf "$file" "${file}.bak" && echo "Backup created: ${file}.bak"
}

create_symlink() {
	local target="$1"
	local link_name="$2"

	create_backup_and_delete "$link_name" && sudo mkdir -p "$(dirname "$link_name")" && sudo ln -sT "$target" "$link_name" && echo "Created symlink: $link_name -> $target"
}

create_dotfiles_symlink() {
	create_symlink "$DOTFILES_DIR/files/$1" "$2"
}

create_copy() {
	local source="$1"
	local destination="$2"

	create_backup_and_delete "$destination" && sudo mkdir -p "$(dirname "$destination")" && sudo cp "$source" "$destination" && echo "Copied $source to $destination"
}

create_recursive_copy() {
	local source="$1"
	local destination="$2"

	create_backup_and_delete "$destination" && sudo mkdir -p "$(dirname "$destination")" && sudo cp -r "$source" "$destination" && echo "Recursively copied $source to $destination"
}

create_dotfiles_copy() {
	create_copy "$DOTFILES_DIR/files/$1" "$2"
}

create_dotfiles_recursive_copy() {
	create_recursive_copy "$DOTFILES_DIR/files/$1" "$2"
}

# FIXME: does not seem to work multiple times when the marker is first line
insert_content_with_marker() {
	local file="$1" marker="$2" content="$3" comment_char_opening="${4:-#}" comment_char_closing="${5:-#}"
	local start="$comment_char_opening AUTOGENERATED START $marker $comment_char_closing"
	local end="$comment_char_opening AUTOGENERATED END $marker $comment_char_closing"

	# Create temp file to preserve original location
	local temp_file=$(mktemp)

	if sudo grep -Fq "$start" "$file" 2>/dev/null; then
		# Replace content between markers
		local start_line=$(sudo grep -Fn "$start" "$file" | cut -d: -f1)
		local end_line=$(sudo grep -Fn "$end" "$file" | cut -d: -f1)

		# Copy before, insert new content, copy after
		sudo sed -n "1,$((start_line - 1))p" "$file" >"$temp_file"
		printf '%s\n%s\n%s\n' "$start" "$content" "$end" >>"$temp_file"
		sudo sed -n "$((end_line + 1)),\$p" "$file" >>"$temp_file"
		sudo cp "$temp_file" "$file"
	else
		# Append new content if markers don't exist
		sudo cp "$file" "$temp_file"
		printf '%s\n%s\n%s\n' "$start" "$content" "$end" >>"$temp_file"
		sudo cp "$temp_file" "$file"
	fi

	rm -f "$temp_file"
	echo "Inserted content with marker $marker in $file"
}

install_packages() {
	local packages=("$@")

	if [ ${#packages[@]} -eq 0 ]; then
		echo "No packages specified for installation."
		return 1
	fi

	echo "Installing packages: ${packages[*]}"
	sudo pacman -S --noconfirm --needed "${packages[@]}"
}

install_yay_packages() {
	local packages=("$@")

	if [ ${#packages[@]} -eq 0 ]; then
		echo "No yay packages specified for installation."
		return 1
	fi

	echo "Installing yay packages: ${packages[*]}"
	yay -S --needed "${packages[@]}"
}
