#!/usr/bin/env bash

install_audio() {
    dots-pkg-install sof-firmware
    dots-pkg-install pipewire wireplumber pipewire-audio pipewire-pulse pipewire-jack
    dots-pkg-install wiremix
}

install_bluetooth() {
    sudo systemctl enable --now bluetooth.service
    dots-pkg-yay-install bluetuith
}

install_clipboard() {
    dots-pkg-install wl-clipboard
}

install_disks() {
    dots-pkg-install gvfs udisks2
    dots-pkg-install udiskie
    dots-pkg-install dust
}

install_docs() {
    dots-pkg-install man-pages tldr
}

install_files_management() {
    dots-pkg-install bat fd ripgrep zoxide fzf
    dots-pkg-install thunar yazi ranger nnn
}

install_files_manipulation() {
    dots-pkg-install jq go-yq
}

install_files_sync() {
    dots-pkg-install rclone syncthing rsync
}

install_fonts() {
    dots-pkg-install ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols

    # FIXME:
    # cargo install --git https://github.com/loichyan/nerdfix.git
}

install_hyprlandia() {
    dots-pkg-install hyprland hyprpaper hyprcursor hyprlock hypridle hyprland-qtutils hyprland-qt-support hyprpolkitagent
    dots-pkg-install xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
    dots-pkg-install qt6-wayland qt5-wayland

    dots-pkg-install cmake meson cpio git gcc
    hyprpm add --force https://github.com/hyprwm/hyprland-plugins $DOTS_HYPRLAND_PLUGINS_VERSION || echo "hyprpm add failed"
    hyprpm update || echo "hyprpm update failed"
    hyprpm enable hyprexpo || echo "hyprpm enable hyprexpo failed"

    dots-pkg-install uwsm libnewt
}

install_monitoring() {
    dots-pkg-install fastfetch btop
}

install_multimedia() {
    dots-pkg-install playerctl
}

install_power() {
    dots-pkg-install upower power-profiles-daemon
}

install_qt() {
    dots-pkg-install kvantum kvantum-qt5
}

install_quickshell() {
    dots-pkg-install qt6-shadertools cli11
    if ! test -e ~/documents/quickshell; then
        git clone https://github.com/Flo-CS/quickshell.git ~/documents/quickshell
    else
        # TODO: Why sudo is required? How to install as user?
        cd ~/documents/quickshell &&
            git pull &&
            cmake -GNinja -B build -DCMAKE_BUILD_TYPE=ReleaseWithDebInfo -DCRASH_REPORTER=OFF &&
            cmake --build build &&
            sudo cmake --install build &&
            cd -
    fi
}

install_screen() {
    dots-pkg-install brightnessctl
}

install_waybar() {
    dots-pkg-install waybar
}

install_wofi() {
    dots-pkg-install wofi
}

install_screenshot() {
    dots-pkg-install hyprshot satty
}

install_audio
install_bluetooth
install_clipboard
install_disks
install_docs
install_files_management
install_files_manipulation
install_files_sync
install_fonts
install_hyprlandia
install_monitoring
install_multimedia
install_power
install_qt
install_quickshell
install_screen
install_waybar
install_wofi
install_screenshot
