#!/usr/bin/env bash

install_docker() {
    dots-pkg-install docker docker-compose
    dots-pkg-yay-install lazydocker
    sudo systemctl enable --now docker.socket # Start on first usage, different from .service which start on boot
}

install_python() {
    dots-pkg-install python-pip
}

install_rust() {
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
}

install_nodejs() {
    dots-pkg-install nvm
    source /usr/share/nvm/init-nvm.sh
    nvm install --lts || echo "nvm install failed, maybe nvm is not properly configured" >&2
}

# TODO: Make a full installation
install_android_studio() {
    dots-pkg-yay-install android-studio
}

# TODO: Make a full installation
install_flutter() {
    dots-pkg-install curl git unzip xz zip glu
    mkdir -p ~/development

    local installed_version=$(flutter --version | grep -oP 'Flutter \K[0-9.]+')
    local target_version="3.35.1"

    if version-ge "$installed_version" "$target_version"; then
        echo "Flutter $installed_version is already installed, skipping installation"
    else
        curl --proto '=https' --tlsv1.2 -sSf https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_$target_version-stable.tar.xz -o /tmp/flutter.tar.xz
        tar -xf /tmp/flutter.tar.xz -C ~/development/

        if ! grep -q 'export PATH="$HOME/development/flutter/bin:$PATH"' ~/.bashrc; then
            echo 'export PATH="$HOME/development/flutter/bin:$PATH"' >>~/.bashrc
        fi
    fi
}

install_neovim() {
    dots-pkg-install neovim
}

install_terminal() {
    curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh | sh

    dots-pkg-install alacritty
    dots-pkg-remove xterm || echo "xterm is already uninstalled, skipping"
    sudo ln -sf /usr/bin/alacritty /usr/bin/xterm # Stupid workaround to allow to run .desktop files that require by default xterm (i don't know how to change it)

    dots-pkg-install starship
}

install_docker
install_python
install_rust
install_nodejs
install_android_studio
install_flutter
install_neovim
install_terminal
