#!/usr/bin/env bash

install_audio() {
    myarchy-pkg-install sof-firmware
    myarchy-pkg-install pipewire wireplumber pipewire-audio pipewire-pulse pipewire-jack
    myarchy-pkg-install wiremix
}

install_bluetooth() {
    sudo systemctl enable --now bluetooth.service
    myarchy-pkg-yay-install bluetuith
}

install_clipboard() {
    myarchy-pkg-install wl-clipboard
}

install_disks() {
    myarchy-pkg-install gvfs udisks2
    myarchy-pkg-install udiskie
    myarchy-pkg-install dust
}

install_docs() {
    myarchy-pkg-install man-pages tldr
}

install_files_management() {
    myarchy-pkg-install bat fd ripgrep zoxide fzf
    myarchy-pkg-install thunar yazi ranger nnn
}

install_files_manipulation() {
    myarchy-pkg-install jq go-yq
}

install_files_sync() {
    myarchy-pkg-install rclone syncthing rsync
}

install_fonts() {
    myarchy-pkg-install ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols

    # FIXME:
    # cargo install --git https://github.com/loichyan/nerdfix.git
}

install_hyprlandia() {
    myarchy-pkg-install hyprland hyprpaper hyprcursor hyprlock hypridle hyprland-qtutils hyprland-qt-support hyprpolkitagent
    myarchy-pkg-install xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
    myarchy-pkg-install qt6-wayland qt5-wayland

    myarchy-pkg-install cmake meson cpio git gcc
    hyprpm add --force https://github.com/hyprwm/hyprland-plugins || echo "hyprpm add failed"
    hyprpm update || echo "hyprpm update failed"
    hyprpm enable hyprexpo || echo "hyprpm enable hyprexpo failed"

    myarchy-pkg-install uwsm libnewt
}

install_monitoring() {
    myarchy-pkg-install fastfetch btop
}

install_multimedia() {
    myarchy-pkg-install playerctl
}

install_power() {
    myarchy-pkg-install upower power-profiles-daemon
}

install_qt() {
    myarchy-pkg-install kvantum kvantum-qt5
}

install_screen() {
    myarchy-pkg-install brightnessctl
}

install_waybar() {
    myarchy-pkg-install waybar
}

install_wofi() {
    myarchy-pkg-install wofi
}

install_screenshot() {
    myarchy-pkg-install hyprshot satty
}

install_mako() {
    myarchy-pkg-install mako
}

install_python_wayland() {
    myarchy-pkg-install python-pywayland
}

install_audio
install_bluetooth
install_clipboard
install_disks
install_docs
install_files_management
install_files_manipulation
install_files_sync
install_fonts
install_hyprlandia
install_monitoring
install_multimedia
install_power
install_qt
install_screen
install_waybar
install_wofi
install_screenshot
install_mako
install_python_wayland
