#!/usr/bin/env bash

install_flatpak() {
    myarchy-pkg-install flatpak
    flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
}

install_git() {
    myarchy-pkg-install git git-filter-repo lazygit git-delta
    myarchy-pkg-yay-install git-credential-oauth
}

install_flatpak
install_git
