#!/usr/bin/env bash

install_backup() {
    dots-pkg-install snapper snap-pac inotify-tools grub-btrfs

    # WARNING: The boot on snapshot part (managed by grub-btrfs) will only work with EndeavourOS because it uses dracut.
    # For raw ArchLinux systems, see grub-btrfs docs for more information and the alternative way to boot on snapshot.

    sudo snapper -c root create-config / || echo "Failed to create snapper config, maybe root config already exists" >&2

    sudo -E dots-backup-file /etc/snapper/configs/root

    sudo snapper -c root set-config ALLOW_USERS="$USER"
    sudo snapper -c root set-config TIMELINE_LIMIT_HOURLY="10"
    sudo snapper -c root set-config TIMELINE_LIMIT_DAILY="5"
    sudo snapper -c root set-config TIMELINE_LIMIT_WEEKLY="3"
    sudo snapper -c root set-config TIMELINE_LIMIT_MONTHLY="0"
    sudo snapper -c root set-config TIMELINE_LIMIT_YEARLY="0"

    sudo systemctl enable --now snapper-timeline.timer snapper-cleanup.timer

    # WARNING: only work on EndeavourOS because it uses dracut
    sudo -E dots-file-insert-with-marker /etc/default/grub-btrfs/config "custom" "GRUB_BTRFS_SNAPSHOT_KERNEL_PARAMETERS=\"rd.live.overlay.overlayfs=1\""

    sudo systemctl enable --now grub-btrfsd
}

install_grub() {
    # os-prober is disabled by default in grub config and it's better for security reasons. But it is useful to detect other OSes and then add them manually to grub.
    windows_boot_partition_path=$(sudo os-prober | grep "Windows Boot Manager" | head -n 1 | cut -d'@' -f1 || echo "")
    if [[ -n $windows_boot_partition_path ]]; then
        echo "detected Windows Boot Manager at: $windows_boot_partition_path"
        windows_boot_partition_uuid=$(sudo blkid -s UUID -o value "$windows_boot_partition_path" 2>/dev/null)
        if [[ -z $windows_boot_partition_uuid ]]; then
            windows_boot_partition_uuid=$(lsblk -no UUID "$windows_boot_partition_path" 2>/dev/null)
            if [[ -z $windows_boot_partition_uuid ]]; then
                echo "unable to retrieve UUID for Windows Boot Manager partition." >&2
                exit 1
            fi
        fi

        echo "Windows Boot Manager UUID: $windows_boot_partition_uuid"
        sudo -E dots-file-insert-with-marker /etc/grub.d/40_custom "windows" "
    menuentry 'Windows Boot Manager' --class windows --class os {
        search --fs-uuid --no-floppy --set=root $windows_boot_partition_uuid
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
    }
    "
    else
        echo "no Windows Boot Manager found. Skipping Windows entry in GRUB."
    fi

    grep -q '^GRUB_DEFAULT=' /etc/default/grub && sudo sed -i 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/' /etc/default/grub

}

install_privileged() {
    sudo -E dots-file-copy install/config/sudoers /etc/sudoers.d/sudoers-default
}

install_backup
install_grub
install_privileged
