# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#e8e8e8"
background = "#0a0a0a"
dim_foreground = "#666666"
bright_foreground = "#e8e8e8"

[colors.cursor]
text = "#e8e8e8"
cursor = "#3a3a3a"

[colors.vi_mode_cursor]
text = "#e8e8e8"
cursor = "#3a3a3a"

[colors.search.matches]
foreground = "#666666"
background = "#1e1e1e"

[colors.search.focused_match]
foreground = "#0a0a0a"
background = "#4a9b5e"

[colors.hints.start]
foreground = "#666666"
background = "#141414"

[colors.hints.end]
foreground = "#3a3a3a"
background = "#141414"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e8e8e8"
background = "#141414"

[colors.selection]
text = "#e8e8e8"
background = "#252525"

[colors.normal]
black = "#1e1e1e"
red = "#d97757"
green = "#4a9b5e"
yellow = "#b8860b"
blue = "#5a8a6b"
magenta = "#7a6b8a"
cyan = "#2d5a36"
white = "#e8e8e8"

[colors.bright]
black = "#3a3a3a"
red = "#e58a73"
green = "#6bb57a"
yellow = "#d4a332"
blue = "#7da495"
magenta = "#9b8aa7"
cyan = "#4a7a55"
white = "#f5f5f5"

[colors.dim]
black = "#3a3a3a"
red = "#b85d42"
green = "#3a7a4a"
yellow = "#9a6b0a"
blue = "#4a6b5a"
magenta = "#5a4b6a"
cyan = "#225a2a"
white = "#e8e8e8"
